//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuts.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseCutsEntities2 : DbContext
    {
        public DatabaseCutsEntities2()
            : base("name=DatabaseCutsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Antrian> Antrians { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_status> Order_status { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Promo> Promoes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Store_detail> Store_detail { get; set; }
        public virtual DbSet<Store_type> Store_type { get; set; }
        public virtual DbSet<Temp_store> Temp_store { get; set; }
        public virtual DbSet<Temp_store_status> Temp_store_status { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
