//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuts.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string User_username { get; set; }
        public string Store_username { get; set; }
        public Nullable<int> Product_id { get; set; }
        public string User_phone { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Status_id { get; set; }
    
        public virtual Order_status Order_status { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}
