//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuts.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Username { get; set; }
        public int Id { get; set; }
        public string Nama { get; set; }
        public string Harga { get; set; }
        public string Average_duration { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Description { get; set; }
        public Nullable<int> Stock { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
