//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuts.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_detail
    {
        public string Username { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Operational_hour { get; set; }
        public string Phone { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
